random_state: 239

dataset:
  training_dataset_dirs:
    - '..\data\split\test'
  validation_dataset_dirs:
    - '..\data\split\valid'
  test_dataset_dirs:
    - '..\data\split\train'
  image_size:
    width: 256
    height: 256
  augmentation: None

dataloader:
  train_batch_size: 2
  val_batch_size: 2
  pin_memory: False
  num_workers: 4

model:
  model_name: 'swinv2'
  model_type: 'tiny-patch4-window16-256'
  device: 'mps'
  save_dir: '.\checkpoints\swin\swin_tiny\run1'

training:
  adele: False
  epoch_num: 4

optimizer:
  name: "AdamW"
  lr: 0.001
  betas:
    - 0.9  # Beta1
    - 0.999  # Beta2

mlflow:
  experiment_name: None # if None, experiment name generating automatically

history:
  draw_plots: True
  draw_result: True
  plots_figure_name: "output.png"
  results_figure_name: "results.png"
