random_state: 239

dataset:
  training_datasets:
    - "/path/to/training_dataset_1"
  validation_datasets:
    - "/path/to/validation_dataset"
  test_datasets:
    - "/path/to/test_dataset"
  image_size:
    width: 256
    height: 256
  augmentation: None

dataloader:
  train_batch_size: 8
  val_batch_size: 4
  pin_memory: True
  num_workers: 4

model:
  model_name: "segformer"
  model_type: "b1"
  device: "cuda"

optimizer:
  name: "AdamW"
  lr: 0.001
  betas:
    - 0.9  # Beta1
    - 0.999  # Beta2

mlflow:
  experiment_name: None # if None, experiment name generating automatically

history:
  draw_plots: True
  draw_results: True
  plots_figure_name: "output.png"
  results_figure_name: "results.png"
