random_state: 239

dataset:
  training_dataset_dirs:
    - '.\data\weakly_segmented\bubbles_split\test'
  validation_dataset_dirs:
    - '.\data\weakly_segmented\bubbles_split\valid'
  test_dataset_dirs:
    - '.\data\weakly_segmented\bubbles_split\train'
  image_size:
    width: 256
    height: 256
  augmentation: None

dataloader:
  train_batch_size: 8
  val_batch_size: 4
  pin_memory: True
  num_workers: 4

model:
  model_name: 'segformer'
  model_type: 'b1'
  device: 'cuda'
  save_dir: '.\checkpoints\segformer\segformer_b1\run1'

training:
  adele: False
  epoch_num: 1

optimizer:
  name: "AdamW"
  lr: 0.001
  betas:
    - 0.9  # Beta1
    - 0.999  # Beta2

mlflow:
  experiment_name: None # if None, experiment name generating automatically

history:
  draw_plots: True
  draw_result: True
  plots_figure_name: "output.png"
  results_figure_name: "results.png"
