thresh: 60
marker_type: small
min_distance: 10
watershed_label_type: image
preprocess:
  single_scale_retinex:
    sigma: 50
  bilateral_filtering:
    diameter: 9
    sigma_color: 75
    sigma_space: 75
  morphological_transform:
    kernel_size: [5, 5]
  gaussian_blur:
    kernel_size: [7, 7]
    sigma_x: 2
  minmax:
    span: [0, 255]
