_target_: src.models.SegFormer
net:
  _target_: transformers.SegformerForSemanticSegmentation.from_pretrained
  pretrained_model_name_or_path: "nvidia/segformer-b2-finetuned-ade-512-512"
  num_labels: 2
  ignore_mismatched_sizes: True
  image_size: ${data.img_size}