random_seed: 239

dataset:
  training_dataset_dirs:
    - '.\data\new\train'
  validation_dataset_dirs:
    - '.\data\new\valid'

  image_size:
    width: 256
    height: 256
  augmentation: None

dataloader:
  train_batch_size: 8
  val_batch_size: 4
  pin_memory: True
  num_workers: 4

model:
  model_name: 'resnet34'
  model_type: ''
  device: 'cuda'
  # save_dir: '.\checkpoints\hrnet\hrnet_test\run1'
  save_dir: None

training:
  adele: False
  epoch_num: 20
  main_metric: "iou"

optimizer:
  name: "Adam"
  lr: 0.00001
  betas:
    - 0.9  # Beta1
    - 0.999  # Beta2
  weight_decay: 0.001

mlflow:
  experiment_name: "deeplab-256-256-full" # if None, experiment name generating automatically

history:
  draw_plots: True
  draw_result: False
  plots_line_width: 8
  plots_fontsize: 20
  plots_figure_name: "output.png"
  results_figure_name: "results.png"
