defaults:
  - model: timm_model  # default model, can be overridden

model:
  _target_: str
  library: str  # model library
  type: str     # model type for transformers (e.g., BERT, etc.)
  config: {}    # model-specific config

timm_model:
  _target_: timm.create_model
  model_name: resnet50
  pretrained: true

transformers_model:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  model_name: bert-base-uncased
  num_labels: 2

smp_model:
  _target_: segmentation_models_pytorch.Unet
  encoder_name: resnet34
  in_channels: 3
  classes: 1
