defaults:
  - arch: hrnet

num_channels: 3
num_classes: 1
threshold: 0.5

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
  weight_decay: 1e-5

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: 15

cls_losses:
  - name: bce
    weight: 0.4
    loss_fn:
      _target_: torch.nn.BCELoss

seg_losses:
  - name: dice
    weight: 0.6
    loss_fn:
      _target_: segmentation_models_pytorch.losses.DiceLoss
      mode: binary
      from_logits: false