checkpoint_path: '..\checkpoints\hrnet\best.pt'
export_path: '..\models\hrnet\hrnet_test.onnx'

input_tensor_shape: [1, 3, 256, 256]

input_names: ['input']
output_names: ['output']

export:
  export_params: True  # store the trained parameter weights inside the model file
  do_constant_folding: True  # whether to execute constant folding for optimization
  verbose: False
  dynamic_axes:
    input: {0: 'batch_size'}
    output: {0: 'batch_size'}
  opset_version: 11

acceleration:
  quantization: True
  quantization_path: '..\models\hrnet\hrnet_q_test.onnx'
  quantization_type: int8

runtime:
  providers: ['CUDAExecutionProvider']