checkpoint_path: '.\runs\segment\train6\weights\best.pt'
export_path: '.\models\onnx\yolov8_seg.onnx'

input_tensor_shape: [1, 3, 256, 256]

input_names: ['input']
output_names: ['output']

export:
  export_params: True  # store the trained parameter weights inside the model file
  do_constant_folding: True  # whether to execute constant folding for optimization
  verbose: True
  dynamic_axes:
    input: {0: 'batch_size'}
    output: {0: 'batch_size'}
  opset_version: 10
  half: False
  simplify: True

