defaults:
  - _self_
  - sam_yolo: sam_yolo
  - watershed: watershed
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

data_dir: 'data'
folder: 'covdor_generated'
device: 'cpu'
combination_type: 'sam_first'

hydra:
  run:
    dir: ../outputs
