defaults:
  - _self_
  - sam_yolo: sam_yolo
  - preprocess: preprocess
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

data_dir: 'data'
folder: 'gt/images'
device: 'cpu'
processes_num: 0

hydra:
  run:
    dir: ../outputs
