defaults:
  - _self_
  - data: data
  - experiment: experiment
  - module: module
  - trainer: trainer
  - preprocess: preprocess
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none


hydra:
  run:
    dir: ../outputs
